### ISSUE TITLE
asff_mapper missing

### ISSUE THREAD

**Issue by jtconnor** [mitre/heimdall_tools#121]
Hi, I'm trying to use the asff_mapper.  The documention includes the asff_mapper, but this mapper seems to be missing from the current release version of heimdall_tools:

```
▶ heimdall_tools --version
1.3.48
▶ heimdall_tools asff_mapper
Could not find command "asff_mapper".
Did you mean?  "sarif_mapper"
```

How should I use the asff_mapper?  Do I need to build and run from repo source?

**Comment by Amndeep7** [comment]
Hi @jtconnor, actually we just pushed out a new ruby release to grab the last bit of work there, so, if you upgrade your version of heimdall_tools, you should be able to use the asff_mapper.

**Comment by jtconnor** [comment]
Thanks for the update @Amndeep7 !

I verified that the heimdall_tools release includes the asff_mapper command:
```
▶ heimdall_tools --version
1.3.49

▶ heimdall_tools asff_mapper
No value provided for required options '--json', '--output'
```

But it looks like the heimdall_tools asff_mapper command isn't able to parse ASFF json:
```
▶ aws securityhub get-findings --region us-east-1 --max-items 100 > ./security-hub-findings.json
▶ heimdall_tools asff_mapper --json ./security-hub-findings.json --output ./output.json
Traceback (most recent call last):
	10: from /usr/local/bin/heimdall_tools:23:in `<main>'
	 9: from /usr/local/bin/heimdall_tools:23:in `load'
	 8: from /Library/Ruby/Gems/2.6.0/gems/heimdall_tools-1.3.49/exe/heimdall_tools:14:in `<top (required)>'
	 7: from /Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	 6: from /Library/Ruby/Gems/2.6.0/gems/heimdall_tools-1.3.49/lib/heimdall_tools/command.rb:44:in `dispatch'
	 5: from /Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	 4: from /Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	 3: from /Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	 2: from /Library/Ruby/Gems/2.6.0/gems/heimdall_tools-1.3.49/lib/heimdall_tools/cli.rb:164:in `asff_mapper'
	 1: from /Library/Ruby/Gems/2.6.0/gems/heimdall_tools-1.3.49/lib/heimdall_tools/cli.rb:164:in `new'
/Library/Ruby/Gems/2.6.0/gems/heimdall_tools-1.3.49/lib/heimdall_tools/asff_mapper.rb:66:in `initialize': Not a findings file nor an individual finding (RuntimeError)
	11: from /usr/local/bin/heimdall_tools:23:in `<main>'
	10: from /usr/local/bin/heimdall_tools:23:in `load'
	 9: from /Library/Ruby/Gems/2.6.0/gems/heimdall_tools-1.3.49/exe/heimdall_tools:14:in `<top (required)>'
	 8: from /Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	 7: from /Library/Ruby/Gems/2.6.0/gems/heimdall_tools-1.3.49/lib/heimdall_tools/command.rb:44:in `dispatch'
	 6: from /Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	 5: from /Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	 4: from /Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	 3: from /Library/Ruby/Gems/2.6.0/gems/heimdall_tools-1.3.49/lib/heimdall_tools/cli.rb:164:in `asff_mapper'
	 2: from /Library/Ruby/Gems/2.6.0/gems/heimdall_tools-1.3.49/lib/heimdall_tools/cli.rb:164:in `new'
	 1: from /Library/Ruby/Gems/2.6.0/gems/heimdall_tools-1.3.49/lib/heimdall_tools/asff_mapper.rb:56:in `initialize'
/Library/Ruby/Gems/2.6.0/gems/heimdall_tools-1.3.49/lib/heimdall_tools/asff_mapper.rb:69:in `rescue in initialize': Invalid ASFF file provided: (RuntimeError)
Exception: Not a findings file nor an individual finding
```

But when I upload the same security-hub-findings.json file to Heimdall Lite, it's able to parse the ASFF file:
![image](https://user-images.githubusercontent.com/6622359/143181388-314b5b5d-71e1-42b1-bee1-f9f9c08c0b02.png)

**Comment by Amndeep7** [comment]
@jtconnor 

It depends on what the security hub output is looking like since the Ruby variant at least does some schema validation before running - there can be implementation differences with the JS variant which is what heimdall is using to autoconvert files.  Specifically if you look at the asff_mapper (https://github.com/mitre/heimdall_tools/blob/5da2c7982cddb92f0d97b941f6cb39df75cac78c/lib/heimdall_tools/asff_mapper.rb#L56), you'll see that the mapper tries to confirm if it's a single finding with the shape of being a json object containing certain attributes like an `AwsAccountId` and so on OR if it's a collection of findings in which case it attempts to do that shape validation against every finding from an array called "Findings" within the json object.  Sometimes certain applications do not output data in those formats, such as Prowler's asff output which required some pre-processing (https://github.com/mitre/heimdall_tools/blob/5da2c7982cddb92f0d97b941f6cb39df75cac78c/lib/heimdall_tools/prowler_mapper.rb#L5) before we can pass the correctly formatted data into the asff mapper.  Can you please confirm what the output of your findings file looks like?

If it doesn't match the assumptions above, would it be possible to send your sample file to me?  Ideally you'd post that file here (with redactions/anonymization of course to do things like removing the aws account id), but we can move off of github if necessary - my email address is amann[at]mitre.org.  We can also potentially communicate on CMS slack or email.
